# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yu5CC0ivszrWLPBXlgz42DL0gwGy2TGb
"""

import streamlit as st
st.title("BMI Calculator")
mass = st.number_input("Enter Weight in kg", step = 0.1)
height = st.number_input("Enter your height in metres", step = 0.1)
button = st.button("Calculate BMI")
if button:
  bmi = mass / (height)**
  st.success(f"Your BMI is {bmi}.")